# Generated by Django 5.0.1 on 2024-01-26 16:19
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
        ('waybills', '0003_move_store')
    ]

    operations = [
        migrations.AlterField('Store', 'id', models.UUIDField(auto_created=False, primary_key=True, serialize=False, verbose_name='ID'))
    ]
