# Generated by Django 3.2.7 on 2022-08-16 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'учетный месяц',
                'verbose_name_plural': 'учетные месяцы',
            },
        ),
        migrations.CreateModel(
            name='Spending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование')),
                ('amount', models.IntegerField(verbose_name='Сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('year', models.IntegerField(default=None, null=True, verbose_name='Учетный год')),
                ('agreed', models.ForeignKey(default='Управляющий', on_delete=django.db.models.deletion.DO_NOTHING, to='spending.agreed', to_field='name', verbose_name='Согласовано')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spending.category', to_field='name', verbose_name='Категория')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department', verbose_name='Заведение')),
                ('month', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spending.month', to_field='name', verbose_name='Учетный месяц')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'расход',
                'verbose_name_plural': 'расходы',
            },
        ),
    ]
