# Generated by Django 3.2.7 on 2022-08-16 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('day', models.DateField(primary_key=True, serialize=False)),
                ('orders_count', models.IntegerField(default=0)),
                ('guest_num', models.IntegerField(default=0)),
                ('costbase_profit', models.FloatField(default=0)),
                ('costbase_markup', models.FloatField(default=0)),
                ('discount_percent', models.FloatField(default=0)),
                ('costbase_product_cost', models.FloatField(default=0)),
                ('costbase_percent', models.FloatField(default=0)),
                ('avg_precheque_time', models.FloatField(default=0)),
                ('guest_num_avg', models.FloatField(default=0)),
                ('sum_avg', models.FloatField(default=0)),
                ('return_sum', models.FloatField(default=0)),
                ('discount_sum', models.FloatField(default=0)),
                ('discount_sum_int', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'stats',
            },
        ),
    ]
