# Generated by Django 5.0.1 on 2024-01-26 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stats',
        ),
    ]
