# Generated by Django 5.0.1 on 2024-01-26 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0001_initial'),
        ('stores', '0001_initial')
    ]

    state_operations = [
        migrations.AlterField('Waybill', 'store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stores.store', verbose_name='Склад')),
        migrations.AlterField('Waybill', 'counteragent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='counteragent', to='stores.store', verbose_name='Контрагент')),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=state_operations
        )
    ]
