# Generated by Django 5.0.1 on 2024-01-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0003_move_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waybillitem',
            name='product_id',
            field=models.UUIDField(),
        ),
    ]
