# Generated by Django 5.0.1 on 2024-01-27 19:37

import django.db.models.deletion

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0004_alter_waybillitem_product_id')
    ]

    operations = [
        migrations.RenameField(
            model_name='waybill',
            old_name='received_by',
            new_name='processed_by'
        ),
        migrations.AlterField(
            model_name='waybill',
            name='processed_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='processed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
