# Generated by Django 5.0.1 on 2024-01-28 09:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0005_rename_waybill_received_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='waybill',
            name='processed_at',
            field=models.BigIntegerField(default=None, null=True),
        )
    ]
