# Generated by Django 3.2.7 on 2022-08-16 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import time


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('waybills', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Writeoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default=None, null=True, verbose_name='Комментарий')),
                ('status', models.CharField(default='Created', max_length=16)),
                ('created_at', models.BigIntegerField(default=time.time)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='writeoff_received_by', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='waybills.store', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'списание',
                'verbose_name_plural': 'списания',
                'db_table': 'writeoffs',
            },
        ),
        migrations.CreateModel(
            name='WriteoffItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('product_id', models.CharField(max_length=36)),
                ('amount', models.FloatField(default=0.0)),
                ('writeoff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='writeoffs.writeoff')),
            ],
            options={
                'db_table': 'writeoffs_items',
            },
        ),
    ]
