# Generated by Django 3.2.7 on 2022-09-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writeoffs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WriteoffReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'причина',
                'verbose_name_plural': 'причины',
                'db_table': 'writeoffs_reasons',
            },
        ),
    ]
