# Generated by Django 3.2.7 on 2022-09-11 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('writeoffs', '0002_writeoffreason'),
    ]

    operations = [
        migrations.AddField(
            model_name='writeoff',
            name='reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='writeoffs.writeoffreason', to_field='name', verbose_name='Причина'),
        ),
    ]
