# Generated by Django 3.2.7 on 2023-04-17 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('writeoffs', '0003_writeoff_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='writeoffreason',
            name='account_id',
            field=models.UUIDField(default=None, null=True, verbose_name='ID счёта'),
        ),
        migrations.AlterField(
            model_name='writeoff',
            name='reason',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='writeoffs.writeoffreason', to_field='name', verbose_name='Причина'),
        ),
    ]
