# Generated by Django 3.2.7 on 2023-04-18 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writeoffs', '0004_auto_20230417_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writeoffreason',
            name='account_id',
            field=models.CharField(default=None, max_length=36, null=True, verbose_name='Идентификатор счёта'),
        ),
    ]
