# Generated by Django 5.0.1 on 2024-01-26 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('writeoffs', '0005_alter_writeoffreason_account_id'),
        ('stores', '0001_initial')
    ]

    state_operations = [
        migrations.AlterField('Writeoff', 'store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stores.store', verbose_name='Склад'))
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=state_operations
        )
    ]
