# Generated by Django 5.0.1 on 2024-01-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writeoffs', '0006_update_refs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writeoffitem',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='writeoffitem',
            name='product_id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='writeoffreason',
            name='account_id',
            field=models.UUIDField(default=None, null=True, verbose_name='Идентификатор счёта'),
        ),
    ]
