# Generated by Django 5.0.1 on 2024-01-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writeoffs', '0007_alter_writeoffitem_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writeoffitem',
            name='name',
        ),
        migrations.AlterField(
            model_name='writeoffitem',
            name='product_id',
            field=models.UUIDField(db_index=True),
        ),
    ]
