# Generated by Django 5.0.1 on 2024-01-30 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writeoffs', '0008_remove_writeoffitem_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='writeoff',
            old_name='received_by',
            new_name='processed_by'
        ),
        migrations.AlterField(
            model_name='writeoff',
            name='processed_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='writeoff_processed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='writeoff',
            name='processed_at',
            field=models.BigIntegerField(default=None, null=True),
        )
    ]
