# Generated by Django 3.2.7 on 2022-08-16 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'заведение',
                'verbose_name_plural': 'заведения',
                'db_table': 'departments',
            },
        ),
    ]
