# Generated by Django 5.0.1 on 2024-01-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='iiko_id',
            field=models.UUIDField(null=True, default=None),
        ),
    ]
