# Generated by Django 5.0.1 on 2024-01-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_department_iiko_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='iiko_name',
            field=models.CharField(null=True, default=None, max_length=128),
        ),
    ]
