# Generated by Django 5.0.1 on 2024-01-26 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_department_iiko_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'подразделение', 'verbose_name_plural': 'подразделения'},
        ),
    ]
