# Generated by Django 3.2.7 on 2022-08-16 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('waybills', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.department', verbose_name='Заведение'),
        ),
        migrations.AddField(
            model_name='user',
            name='stores',
            field=models.ManyToManyField(blank=True, to='waybills.Store', verbose_name='склады'),
        ),
    ]
