# Generated by Django 5.0.1 on 2024-01-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_update_refs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_view_dashboard', 'Просмотр дэшборда'), ('can_view_hungry', 'Просмотр отчётов Hungry Bird 2.0'), ('can_add_waybills', 'Создание накладных'), ('can_view_waybills', 'Просмотр накладных'), ('can_view_guests', 'Просмотр гостей'), ('can_register_users', 'Взаимодействие с заявками на регистрацию'), ('can_add_writeoffs', 'Создание списаний'), ('can_view_writeoffs', 'Просмотр списаний'), ('is_disposer', 'Управляющий'), ('is_accountant', 'Бухгалтер')], 'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
        migrations.AlterField(
            model_name='registerrequest',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
